#Nombre del ms para Eureka
spring.application.name=sophic-cliente

#Puerto que usa el ms
server.port= 8081

#CONFIGURACION PARA LA CONEXION CON LA BD:

#Url para la bd
spring.datasource.url= jdbc:mysql://localhost:3306/sophic_cliente?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

#Busqueda del usuario como "root"
spring.datasource.username=root

#Ingreso del user con contraseña (si se deja vacío el campo entonces no se requiere contraseña)
spring.datasource.password=

#Busqueda de la bd con el driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#CONFIGURACION PARA EL FRAMEWORK DE JPA: 

#Cuando se conecte, se actualiza automaticamente la bd ya que hibernate lee las clases java y crea/actualiza las tablas.
spring.jpa.hibernate.ddl-auto=update

#Muestra en la consola todas las sentencias SQL que spring boot ejecuta 
spring.jpa.show-sql=true

#Esto le dice a hibernate la forma de traducir las clases java (en este caso a consultas SQL)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración del Cliente Eureka (para registrarse en el servidor)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/